= Konfigurator lamp

== Opis klienta
Klientem jest firma produkująca i sprzedająca eksluzywne oświetlenie. W ofercie znajduje się kilkadziesiąt różnych lamp.
Każdy z dostępnych produktów jest możliwy do konfiguracji przez zamawiającego.

== Ogólny opis konfiguratora
Należy zaimplementować konfigurator, który umożliwi klientowi wybór i konfigurację lampy. Ważne, żeby na etapie konfiguracji lampy
prezentować klientowi wybraną konfigurację za pomocą dostarczonych renderów.
Konfiguracja będzie składała się z następujących kroków:

. Lampy są podzielone na grupy (linie) produktowe i w pierwszym kroku trzeba umożliwić wybór linii.
. Dla wybranej linii należy zaprezentować lampy z tej linii i umożliwić wybór konkretnego modelu
. Dla wybranej konkrentej lampy należy umożliwić jej konfigurację - dla poszczególnych części lampy można wybrać kolor z zadanej palety (ok 15 kolorów).
.. Konfigurator powinien prezentować render lampy wraz z wybranymi kolorami
.. Nie wszystkie kombinacje kolorów są dozwolone. W przypadku wybrania niepasującego koloru dla jakiejś części pozostałe muszą zostać zmienione tak, aby konfiguracja była prawidłowa





https://sztukakodu.pl/jak-najlepiej-uczyc-sie-springa-poprzez-praktyke-15-pomyslow-na-projekty-ktore-pomoga-ci-w-nauce